//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputactions/PlayerAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerAction"",
    ""maps"": [
        {
            ""name"": ""Love"",
            ""id"": ""39bed7ba-80c4-4c21-a12b-0ebe94584c01"",
            ""actions"": [
                {
                    ""name"": ""OneJump"",
                    ""type"": ""Button"",
                    ""id"": ""75fc7c7f-5269-4bca-8285-567ec6671a4c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OneShot"",
                    ""type"": ""Button"",
                    ""id"": ""34c5b069-097b-4f06-9a86-efac9b3cc0b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TwoJump"",
                    ""type"": ""Button"",
                    ""id"": ""c6eb2cce-ce4e-4135-943d-47a81c121069"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TwoShot"",
                    ""type"": ""Button"",
                    ""id"": ""04102c3f-93dc-4945-865c-bb9a87e43487"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""82acaa1d-5228-4762-acbb-e6784c3d1b28"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Result"",
                    ""type"": ""Button"",
                    ""id"": ""eb3dc895-1bd5-4c2c-83e3-e168c6e07bd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0037166f-328f-4364-b1bd-14e0e0775acf"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""OneJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7486890d-ace7-467c-9448-0f0007fc5737"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""OneJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f0b1860-3f0c-4cbf-902b-bfe0a51e86b5"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""TwoJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74f971d3-9dbf-4fa1-a85f-3d4bbf276d39"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""TwoJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f73a2257-9e7c-40a7-924a-be098e537054"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""TwoShot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58db6deb-94fb-4b3e-a0b5-d038084a2ea2"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""TwoShot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb1de613-d5b5-4a72-aa4b-19f2346a9faa"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""OneShot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa57ddf1-6bf1-4943-a46e-28650fb63ea4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""OneShot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a94d818d-c240-4650-a364-c268ed3fff22"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5996813c-d661-4b0b-94b1-057a0d3e7913"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3e885f7-96b1-4644-99f0-3d3d17404c4e"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f1deb12-ca6c-459f-80e7-7f7cdae6a4a8"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Result"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a9f3817-a46d-4f58-a557-c86f561e4e6f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Result"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Rival"",
            ""id"": ""d8924df9-a9f1-4e64-8641-fb410af4dc62"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""cc4e7e3e-14df-4a65-831d-0498822f18bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shot"",
                    ""type"": ""Button"",
                    ""id"": ""84088310-d567-462f-8f22-55f20230d856"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""99b95d44-c317-4d46-beeb-8af30df55e5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Result"",
                    ""type"": ""Button"",
                    ""id"": ""cd87346a-9d46-4bda-badd-4c555b110a16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a95aa21a-7b22-4751-84ec-ecddedcb3ae4"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19035f1d-f130-45ae-9e10-567c0ef5c9ea"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Shot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""678fb348-dabb-46be-b4f1-abfeaff01c45"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86922807-f5eb-49f5-a3d0-a09620dc5202"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Result"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Love
        m_Love = asset.FindActionMap("Love", throwIfNotFound: true);
        m_Love_OneJump = m_Love.FindAction("OneJump", throwIfNotFound: true);
        m_Love_OneShot = m_Love.FindAction("OneShot", throwIfNotFound: true);
        m_Love_TwoJump = m_Love.FindAction("TwoJump", throwIfNotFound: true);
        m_Love_TwoShot = m_Love.FindAction("TwoShot", throwIfNotFound: true);
        m_Love_Pause = m_Love.FindAction("Pause", throwIfNotFound: true);
        m_Love_Result = m_Love.FindAction("Result", throwIfNotFound: true);
        // Rival
        m_Rival = asset.FindActionMap("Rival", throwIfNotFound: true);
        m_Rival_Jump = m_Rival.FindAction("Jump", throwIfNotFound: true);
        m_Rival_Shot = m_Rival.FindAction("Shot", throwIfNotFound: true);
        m_Rival_Pause = m_Rival.FindAction("Pause", throwIfNotFound: true);
        m_Rival_Result = m_Rival.FindAction("Result", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Love
    private readonly InputActionMap m_Love;
    private List<ILoveActions> m_LoveActionsCallbackInterfaces = new List<ILoveActions>();
    private readonly InputAction m_Love_OneJump;
    private readonly InputAction m_Love_OneShot;
    private readonly InputAction m_Love_TwoJump;
    private readonly InputAction m_Love_TwoShot;
    private readonly InputAction m_Love_Pause;
    private readonly InputAction m_Love_Result;
    public struct LoveActions
    {
        private @PlayerAction m_Wrapper;
        public LoveActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @OneJump => m_Wrapper.m_Love_OneJump;
        public InputAction @OneShot => m_Wrapper.m_Love_OneShot;
        public InputAction @TwoJump => m_Wrapper.m_Love_TwoJump;
        public InputAction @TwoShot => m_Wrapper.m_Love_TwoShot;
        public InputAction @Pause => m_Wrapper.m_Love_Pause;
        public InputAction @Result => m_Wrapper.m_Love_Result;
        public InputActionMap Get() { return m_Wrapper.m_Love; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LoveActions set) { return set.Get(); }
        public void AddCallbacks(ILoveActions instance)
        {
            if (instance == null || m_Wrapper.m_LoveActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LoveActionsCallbackInterfaces.Add(instance);
            @OneJump.started += instance.OnOneJump;
            @OneJump.performed += instance.OnOneJump;
            @OneJump.canceled += instance.OnOneJump;
            @OneShot.started += instance.OnOneShot;
            @OneShot.performed += instance.OnOneShot;
            @OneShot.canceled += instance.OnOneShot;
            @TwoJump.started += instance.OnTwoJump;
            @TwoJump.performed += instance.OnTwoJump;
            @TwoJump.canceled += instance.OnTwoJump;
            @TwoShot.started += instance.OnTwoShot;
            @TwoShot.performed += instance.OnTwoShot;
            @TwoShot.canceled += instance.OnTwoShot;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Result.started += instance.OnResult;
            @Result.performed += instance.OnResult;
            @Result.canceled += instance.OnResult;
        }

        private void UnregisterCallbacks(ILoveActions instance)
        {
            @OneJump.started -= instance.OnOneJump;
            @OneJump.performed -= instance.OnOneJump;
            @OneJump.canceled -= instance.OnOneJump;
            @OneShot.started -= instance.OnOneShot;
            @OneShot.performed -= instance.OnOneShot;
            @OneShot.canceled -= instance.OnOneShot;
            @TwoJump.started -= instance.OnTwoJump;
            @TwoJump.performed -= instance.OnTwoJump;
            @TwoJump.canceled -= instance.OnTwoJump;
            @TwoShot.started -= instance.OnTwoShot;
            @TwoShot.performed -= instance.OnTwoShot;
            @TwoShot.canceled -= instance.OnTwoShot;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Result.started -= instance.OnResult;
            @Result.performed -= instance.OnResult;
            @Result.canceled -= instance.OnResult;
        }

        public void RemoveCallbacks(ILoveActions instance)
        {
            if (m_Wrapper.m_LoveActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILoveActions instance)
        {
            foreach (var item in m_Wrapper.m_LoveActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LoveActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LoveActions @Love => new LoveActions(this);

    // Rival
    private readonly InputActionMap m_Rival;
    private List<IRivalActions> m_RivalActionsCallbackInterfaces = new List<IRivalActions>();
    private readonly InputAction m_Rival_Jump;
    private readonly InputAction m_Rival_Shot;
    private readonly InputAction m_Rival_Pause;
    private readonly InputAction m_Rival_Result;
    public struct RivalActions
    {
        private @PlayerAction m_Wrapper;
        public RivalActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Rival_Jump;
        public InputAction @Shot => m_Wrapper.m_Rival_Shot;
        public InputAction @Pause => m_Wrapper.m_Rival_Pause;
        public InputAction @Result => m_Wrapper.m_Rival_Result;
        public InputActionMap Get() { return m_Wrapper.m_Rival; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RivalActions set) { return set.Get(); }
        public void AddCallbacks(IRivalActions instance)
        {
            if (instance == null || m_Wrapper.m_RivalActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RivalActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Shot.started += instance.OnShot;
            @Shot.performed += instance.OnShot;
            @Shot.canceled += instance.OnShot;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Result.started += instance.OnResult;
            @Result.performed += instance.OnResult;
            @Result.canceled += instance.OnResult;
        }

        private void UnregisterCallbacks(IRivalActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Shot.started -= instance.OnShot;
            @Shot.performed -= instance.OnShot;
            @Shot.canceled -= instance.OnShot;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Result.started -= instance.OnResult;
            @Result.performed -= instance.OnResult;
            @Result.canceled -= instance.OnResult;
        }

        public void RemoveCallbacks(IRivalActions instance)
        {
            if (m_Wrapper.m_RivalActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRivalActions instance)
        {
            foreach (var item in m_Wrapper.m_RivalActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RivalActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RivalActions @Rival => new RivalActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface ILoveActions
    {
        void OnOneJump(InputAction.CallbackContext context);
        void OnOneShot(InputAction.CallbackContext context);
        void OnTwoJump(InputAction.CallbackContext context);
        void OnTwoShot(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnResult(InputAction.CallbackContext context);
    }
    public interface IRivalActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnShot(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnResult(InputAction.CallbackContext context);
    }
}
